### ISSUE TITLE
Support for react 18.x.x

### ISSUE THREAD

**Issue by ShaktiSinghJD** [inductiveautomation/ignition-sdk-examples#102]
Do we have any plan of react migration to  react:18.x.x in near future ?

**Comment by ynejati** [comment]
Yes, we have plans to do so soon.  Specifically the Perspective component examples.  Appreciate the reminder.  We will move this up in the queue.

**Comment by KathyApplebaum** [comment]
Going to close this issue. I've updated the Home Connect example to match the current Ignition SDK and will push an update for the Perspective component examples soon.
