### ISSUE TITLE
Webpack version

### ISSUE THREAD

**Issue by bikemurt** [inductiveautomation/ignition-sdk-examples#103]
Edit: referring to the **gateway-webpage** example

Not an issue with the source code, but wanted to post this here in case it helps anyone else.

I wasn't able to build the status page using react/webpack because I was using an outdated version of webpack (4.5). After upgrading using `npm install webpack@latest` the build worked fine.

Prior to upgrading I kept getting this error, which people have talked about (a lot) on stack exchange: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

Seems like the "hashFunction" change is a red herring - as long as webpack gets updated, should work as expected.

**Comment by KathyApplebaum** [comment]
Thanks for the comment! I'll go ahead and close this issue since it's not a source code thing.
