### ISSUE TITLE
can't build with gradle

### ISSUE THREAD

**Issue by MaxCarritt** [inductiveautomation/ignition-sdk-examples#48]
Hi, trying to get the perspective examples going with the instructions here:
https://github.com/inductiveautomation/ignition-sdk-examples/tree/master/perspective-component

I've installed everything, and run  ./gradlew buildModule ( ./gradlew.sh doesn't exist). 

I get the following: 

`Downloading https://services.gradle.org/distributions/gradle-5.2.1-all.zip
..............................................................................................................................

Welcome to Gradle 5.2.1!

Here are the highlights of this release:
 - Define sets of dependencies that work together with Java Platform plugin
 - New C++ plugins with dependency management built-in
 - New C++ project types for gradle init
 - Service injection into plugins and project extensions

For more details see https://docs.gradle.org/5.2.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :collectToModlDeps
Copying toModl dependencies to perspective-component/build/libs

> Task :web:npmSetup
/home/max/ignition-sdk-examples/perspective-component/web/.gradle/npm/npm-v6.4.1/bin/npm -> /home/max/ignition-sdk-examples/perspective-component/web/.gradle/npm/npm-v6.4.1/lib/node_modules/npm/bin/npm-cli.js
/home/max/ignition-sdk-examples/perspective-component/web/.gradle/npm/npm-v6.4.1/bin/npx -> /home/max/ignition-sdk-examples/perspective-component/web/.gradle/npm/npm-v6.4.1/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.4.1
added 387 packages from 770 contributors in 7.16s

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/max/.config │
└───────────────────────────────────────────────────────┘

> Task :web:yarnSetup
/home/max/ignition-sdk-examples/perspective-component/web/.gradle/yarn/yarn-v1.15.2/bin/yarnpkg -> /home/max/ignition-sdk-examples/perspective-component/web/.gradle/yarn/yarn-v1.15.2/lib/node_modules/yarn/bin/yarn.js
/home/max/ignition-sdk-examples/perspective-component/web/.gradle/yarn/yarn-v1.15.2/bin/yarn -> /home/max/ignition-sdk-examples/perspective-component/web/.gradle/yarn/yarn-v1.15.2/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.15.2
added 1 package in 0.521s

┌───────────────────────────────────────────────────────┐
│                npm update check failed                │
│          Try running with sudo or get access          │
│         to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/max/.config │
└───────────────────────────────────────────────────────┘

> Task :web:yarn FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':web:yarn'.
> File '/home/max/ignition-sdk-examples/perspective-component/web/yarn.lock' specified for property '$2' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 2s
8 actionable tasks: 8 executed`

**Comment by PerryAJ** [comment]
Hi Max, 

I was able to confirm both issues you've reported.  I'm looking into them and will get a fix up asap.  Thanks for bringing this to our attention!
