### ISSUE TITLE
Can't Build with Gradle

### ISSUE THREAD

**Issue by jnylaan** [inductiveautomation/ignition-sdk-examples#59]
The path to the maven.teamdev.com is showing as not available. Is there another path to this repository?

> Could not resolve all files for configuration ':common:compileClasspath'.
   > Could not resolve com.inductiveautomation.ignitionsdk:ignition-common:8.1.0.
     Required by:
         project :common
      > Could not resolve com.inductiveautomation.ignitionsdk:ignition-common:8.1.0.
         > Could not get resource 'http://maven.teamdev.com/repository/products/com/inductiveautomation/ignitionsdk/ignition-common/8.1.0/ignition-common-8.1.0.pom'.
            > Could not HEAD 'https://maven.teamdev.com/repository/products/com/inductiveautomation/ignitionsdk/ignition-common/8.1.0/ignition-common-8.1.0.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.inductiveautomation.ignitionsdk:perspective-common:8.1.0.
     Required by:
         project :common
      > Could not resolve com.inductiveautomation.ignitionsdk:perspective-common:8.1.0.
         > Could not get resource 'http://maven.teamdev.com/repository/products/com/inductiveautomation/ignitionsdk/perspective-common/8.1.0/perspective-common-8.1.0.pom'.
            > Could not HEAD 'https://maven.teamdev.com/repository/products/com/inductiveautomation/ignitionsdk/perspective-common/8.1.0/perspective-common-8.1.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by PerryAJ** [comment]
Thanks for reporting.  Indeed, Teamdev has changed repo URLS.   You can update your project with the [updated repo details], and I'll be pushing a change to update the example as well.

As a suggestion, if you update the teamdev url yourself, I'd recommend moving it _below_ the inductive automation entries.

**Comment by PerryAJ** [comment]
Can you try the changes submitted in the attached PR and let me know if it resolves the issue for you?

I don't think teamdev should be necessary now at all with this change, as it's proxied as part of our thirdparty artifact repo.

**Comment by jnylaan** [comment]
Yes, that worked thank you for the very quick response!
