### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by cxk297** [inductiveautomation/ignition-sdk-examples#67]
See Below:

:~/Dev/Ignition/ignition-sdk-examples-master/perspective-component$ ./gradlew buildModule
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'perspective-component'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.inductiveautomation.gradle:ignition-module-plugin:1.2.10-SNAPSHOT.
     Required by:
         project :
      > Could not resolve com.inductiveautomation.gradle:ignition-module-plugin:1.2.10-SNAPSHOT.
         > Unable to load Maven meta-data from https://nexus.inductiveautomation.com/repository/inductiveautomation-thirdparty/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://nexus.inductiveautomation.com/repository/inductiveautomation-thirdparty/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://nexus.inductiveautomation.com/repository/inductiveautomation-thirdparty/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml'.
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.inductiveautomation.gradle:ignition-module-plugin:1.2.10-SNAPSHOT.
         > Unable to load Maven meta-data from https://nexus.inductiveautomation.com/repository/inductiveautomation-releases/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://nexus.inductiveautomation.com/repository/inductiveautomation-releases/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://nexus.inductiveautomation.com/repository/inductiveautomation-releases/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml'.
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.inductiveautomation.gradle:ignition-module-plugin:1.2.10-SNAPSHOT.
         > Unable to load Maven meta-data from https://nexus.inductiveautomation.com/repository/inductiveautomation-snapshots/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://nexus.inductiveautomation.com/repository/inductiveautomation-snapshots/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://nexus.inductiveautomation.com/repository/inductiveautomation-snapshots/com/inductiveautomation/gradle/ignition-module-plugin/1.2.10-SNAPSHOT/maven-metadata.xml'.
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

**Comment by kevinherron** [comment]
Are you in an environment with a proxy or something?

This suggests that the certificate from nexus.inductiveautomation.com is not trusted: 
```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

However the certificate presented is a legitimate certificate signed by a CA and `./gradlew buildModule` works without issue for me.
