### ISSUE TITLE
Settings page fields not properly displayed

### ISSUE THREAD

**Issue by Freeno83** [inductiveautomation/ignition-sdk-examples#79]
When doing a fresh clone of the web page example, building it, and installing, The settings field labels show up like this:

![image](https://user-images.githubusercontent.com/60759127/135720098-c3b0df77-535d-4e8d-ac6d-1b32d08deb4d.png)

Alternatively in my own project based on this example, I can get the settings fields to appear:

![image](https://user-images.githubusercontent.com/60759127/135720214-a6f45baf-cea8-461b-8749-2b66f30214fc.png)

But the navigation links appear like this:

![image](https://user-images.githubusercontent.com/60759127/135720184-250e4949-02c2-41ab-b93a-7987415d8b5d.png)

Because the fields are not working in the example and I am struggling to get them working elsewhere I want to ask if there is any  best practices or rules that must be adhered to in order to get all navigation and settings fields labels to appear?

Thanks,
Nick

**Comment by KathyApplebaum** [comment]
Closing this as it will be moot with the coming release of 8.3 and its associated examples
