### ISSUE TITLE
@inductiveautomation/perspective-client@2.1.8 uses vulnerable library moment "^2.20.1"

### ISSUE THREAD

**Issue by bradder555** [inductiveautomation/ignition-sdk-examples#87]
similar to issue #86 , many of the packages used by perspective-client are out by a few major releases. 

Consequently, there are a number of security issues

```
"@inductiveautomation/perspective-client@2.1.8", "@inductiveautomation/perspective-client@^2.1.8":
  version "2.1.8"
  resolved "https://nexus.inductiveautomation.com/repository/node-packages/@inductiveautomation/perspective-
...
...
    mobx-react "^6.1.4"
    mobx-react-lite "^1.5.0"
    moment "2.20.1"
```

[https://security.snyk.io/vuln/SNYK-JS-MOMENT-2440688](https://security.snyk.io/vuln/SNYK-JS-MOMENT-2440688)

please provide a new release of perspective-client, etc

please consider using dependabot in your repos

**Comment by jjcoffman** [comment]
Hi bradder555, thanks for the issue!
This is already an open and outstanding ticket internally (IGN-5570) Which i opened a few sprints back. we are hoping to address it soon!

**Comment by KathyApplebaum** [comment]
PR109 addresses this.
