### ISSUE TITLE
Perspective Component Example uses EoL gradle plugin

### ISSUE THREAD

**Issue by keith-gamble** [inductiveautomation/ignition-sdk-examples#89]
Currently in the Perspective Component example it is using an EoL gradle plugin that was originally built, and left in nexus for backwards compatibility reasons (per @PerryAJ )

It would be better for end-users if it was switched to the more up-to-date version that is open sourced.

Up-to-date version: https://github.com/inductiveautomation/ignition-module-tools

Per Forum post here: https://forum.inductiveautomation.com/t/maven-plugin-post-but-with-gradle/61879/14?u=kgamble

**Comment by PerryAJ** [comment]
@keith-gamble - thanks for submitting this issue to remind me to give this some attention.  I actually have a PR up already with the needed changes (#88), so if you're looking for an example as the basis for your own migrations, it should be almost good to go based on the branch I have there.  I just need to add some better documentation on the frontend integration changes, but it's functional for me.  Let me know if you have any questions.
