### ISSUE TITLE
The last commit of the "perspective module" example cannot be built.

### ISSUE THREAD

**Issue by Skrys33** [inductiveautomation/ignition-sdk-examples#94]
Hello,

The last commit of the "perspective module" example cannot be built.
I have the impression that gradle does not find my sign.props file.

Command : 
./gradlew build --stacktrace

Error : 
Some problems were found with the configuration of task ':signModule' (type 'SignModule').
  - In plugin 'io.ia.sdk.modl' type 'io.ia.sdk.gradle.modl.task.SignModule' property 'certFile' specifies file 'C:\Users\Enzo\Documents\tmp\perspective-component\null' which doesn't exist.

**Comment by PerryAJ** [comment]
Hi Skrys33,

The most recent changes to the perspective example bring a number of significant updates to the project.  The most significant of which is that we've migrated away from the old/deprecated module plugin, and to our [newer open-sourced plugin](https://github.com/inductiveautomation/ignition-module-tools/tree/master/gradle-module-plugin).  This change altered how credentials are dealt with - we no longer use a sign.props file, but instead resolve from [gradle properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties).

Updating to the new structure should be pretty simple - there was some renaming, and slight changes to the plugin configuration (all already represented in the perspective examples), so if you have outstanding modules using the old tool, it should be a fairly painless change. 

Take a look at the linked project/docs and let us know if you have any questions/difficulties.
