### ISSUE TITLE
can`t connect to siemens s1500 PLC

### ISSUE THREAD

**Issue by singsong2016** [inductiveautomation/ignition-sdk-examples#97]
i can`t connect to siemens 1500 PLC through s7 protocl, though opc ua server is ok.
in ignition gateway page, it lists for siemens driver info as thus:

Siemens Drivers | 6.1.25 (b2023021409) | Siemens S7-300, S7-400 and S7-1200 drivers.

we can see that s7-1500 is not included in the newest siemens drivers package, while in device connection page, there is option for s7-1500 PLC.

**Comment by kevinherron** [comment]
You are in the wrong place, contact Inductive Automation support at https://support.inductiveautomation.com/hc/en-us

**Comment by singsong2016** [comment]
thanks ,buddy
